/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiEmployeesRouteImport } from './routes/ai-employees'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as WorkspaceSetupRouteImport } from './routes/workspace-setup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard.appointments'
import { Route as DashboardAutomationsRouteImport } from './routes/dashboard.automations'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard.conversations'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard.integrations'
import { Route as DashboardKnowledgeBaseRouteImport } from './routes/dashboard.knowledge-base'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardAiEmployeesIndexRouteImport } from './routes/dashboard.ai-employees.index'
import { Route as DashboardAiEmployeesFollowUpRouteImport } from './routes/dashboard.ai-employees.follow-up'
import { Route as DashboardAiEmployeesReceptionistRouteImport } from './routes/dashboard.ai-employees.receptionist'
import { Route as DashboardAiEmployeesSalesRouteImport } from './routes/dashboard.ai-employees.sales'
import { Route as DashboardAiEmployeesSupportRouteImport } from './routes/dashboard.ai-employees.support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmployeesRoute = AiEmployeesRouteImport.update({
  id: '/ai-employees',
  path: '/ai-employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSetupRoute = WorkspaceSetupRouteImport.update({
  id: '/workspace-setup',
  path: '/workspace-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomationsRoute = DashboardAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeBaseRoute = DashboardKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiEmployeesIndexRoute =
  DashboardAiEmployeesIndexRouteImport.update({
    id: '/ai-employees/',
    path: '/ai-employees/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAiEmployeesFollowUpRoute =
  DashboardAiEmployeesFollowUpRouteImport.update({
    id: '/ai-employees/follow-up',
    path: '/ai-employees/follow-up',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAiEmployeesReceptionistRoute =
  DashboardAiEmployeesReceptionistRouteImport.update({
    id: '/ai-employees/receptionist',
    path: '/ai-employees/receptionist',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAiEmployeesSalesRoute =
  DashboardAiEmployeesSalesRouteImport.update({
    id: '/ai-employees/sales',
    path: '/ai-employees/sales',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAiEmployeesSupportRoute =
  DashboardAiEmployeesSupportRouteImport.update({
    id: '/ai-employees/support',
    path: '/ai-employees/support',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-employees': typeof AiEmployeesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/workspace-setup': typeof WorkspaceSetupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/automations': typeof DashboardAutomationsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/knowledge-base': typeof DashboardKnowledgeBaseRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ai-employees/follow-up': typeof DashboardAiEmployeesFollowUpRoute
  '/dashboard/ai-employees/receptionist': typeof DashboardAiEmployeesReceptionistRoute
  '/dashboard/ai-employees/sales': typeof DashboardAiEmployeesSalesRoute
  '/dashboard/ai-employees/support': typeof DashboardAiEmployeesSupportRoute
  '/dashboard/ai-employees/': typeof DashboardAiEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-employees': typeof AiEmployeesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/workspace-setup': typeof WorkspaceSetupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/automations': typeof DashboardAutomationsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/knowledge-base': typeof DashboardKnowledgeBaseRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ai-employees/follow-up': typeof DashboardAiEmployeesFollowUpRoute
  '/dashboard/ai-employees/receptionist': typeof DashboardAiEmployeesReceptionistRoute
  '/dashboard/ai-employees/sales': typeof DashboardAiEmployeesSalesRoute
  '/dashboard/ai-employees/support': typeof DashboardAiEmployeesSupportRoute
  '/dashboard/ai-employees': typeof DashboardAiEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-employees': typeof AiEmployeesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/workspace-setup': typeof WorkspaceSetupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/automations': typeof DashboardAutomationsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/knowledge-base': typeof DashboardKnowledgeBaseRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ai-employees/follow-up': typeof DashboardAiEmployeesFollowUpRoute
  '/dashboard/ai-employees/receptionist': typeof DashboardAiEmployeesReceptionistRoute
  '/dashboard/ai-employees/sales': typeof DashboardAiEmployeesSalesRoute
  '/dashboard/ai-employees/support': typeof DashboardAiEmployeesSupportRoute
  '/dashboard/ai-employees/': typeof DashboardAiEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-employees'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/solutions'
    | '/workspace-setup'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/automations'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/integrations'
    | '/dashboard/knowledge-base'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/ai-employees/follow-up'
    | '/dashboard/ai-employees/receptionist'
    | '/dashboard/ai-employees/sales'
    | '/dashboard/ai-employees/support'
    | '/dashboard/ai-employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-employees'
    | '/contact'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/solutions'
    | '/workspace-setup'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/automations'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/integrations'
    | '/dashboard/knowledge-base'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/ai-employees/follow-up'
    | '/dashboard/ai-employees/receptionist'
    | '/dashboard/ai-employees/sales'
    | '/dashboard/ai-employees/support'
    | '/dashboard/ai-employees'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-employees'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/solutions'
    | '/workspace-setup'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/automations'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/integrations'
    | '/dashboard/knowledge-base'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/ai-employees/follow-up'
    | '/dashboard/ai-employees/receptionist'
    | '/dashboard/ai-employees/sales'
    | '/dashboard/ai-employees/support'
    | '/dashboard/ai-employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiEmployeesRoute: typeof AiEmployeesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  WorkspaceSetupRoute: typeof WorkspaceSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-employees': {
      id: '/ai-employees'
      path: '/ai-employees'
      fullPath: '/ai-employees'
      preLoaderRoute: typeof AiEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-setup': {
      id: '/workspace-setup'
      path: '/workspace-setup'
      fullPath: '/workspace-setup'
      preLoaderRoute: typeof WorkspaceSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automations': {
      id: '/dashboard/automations'
      path: '/automations'
      fullPath: '/dashboard/automations'
      preLoaderRoute: typeof DashboardAutomationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge-base': {
      id: '/dashboard/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/dashboard/knowledge-base'
      preLoaderRoute: typeof DashboardKnowledgeBaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-employees/': {
      id: '/dashboard/ai-employees/'
      path: '/ai-employees'
      fullPath: '/dashboard/ai-employees/'
      preLoaderRoute: typeof DashboardAiEmployeesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-employees/follow-up': {
      id: '/dashboard/ai-employees/follow-up'
      path: '/ai-employees/follow-up'
      fullPath: '/dashboard/ai-employees/follow-up'
      preLoaderRoute: typeof DashboardAiEmployeesFollowUpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-employees/receptionist': {
      id: '/dashboard/ai-employees/receptionist'
      path: '/ai-employees/receptionist'
      fullPath: '/dashboard/ai-employees/receptionist'
      preLoaderRoute: typeof DashboardAiEmployeesReceptionistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-employees/sales': {
      id: '/dashboard/ai-employees/sales'
      path: '/ai-employees/sales'
      fullPath: '/dashboard/ai-employees/sales'
      preLoaderRoute: typeof DashboardAiEmployeesSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-employees/support': {
      id: '/dashboard/ai-employees/support'
      path: '/ai-employees/support'
      fullPath: '/dashboard/ai-employees/support'
      preLoaderRoute: typeof DashboardAiEmployeesSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardAutomationsRoute: typeof DashboardAutomationsRoute
  DashboardConversationsRoute: typeof DashboardConversationsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardKnowledgeBaseRoute: typeof DashboardKnowledgeBaseRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAiEmployeesFollowUpRoute: typeof DashboardAiEmployeesFollowUpRoute
  DashboardAiEmployeesReceptionistRoute: typeof DashboardAiEmployeesReceptionistRoute
  DashboardAiEmployeesSalesRoute: typeof DashboardAiEmployeesSalesRoute
  DashboardAiEmployeesSupportRoute: typeof DashboardAiEmployeesSupportRoute
  DashboardAiEmployeesIndexRoute: typeof DashboardAiEmployeesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardAutomationsRoute: DashboardAutomationsRoute,
  DashboardConversationsRoute: DashboardConversationsRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardKnowledgeBaseRoute: DashboardKnowledgeBaseRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAiEmployeesFollowUpRoute: DashboardAiEmployeesFollowUpRoute,
  DashboardAiEmployeesReceptionistRoute: DashboardAiEmployeesReceptionistRoute,
  DashboardAiEmployeesSalesRoute: DashboardAiEmployeesSalesRoute,
  DashboardAiEmployeesSupportRoute: DashboardAiEmployeesSupportRoute,
  DashboardAiEmployeesIndexRoute: DashboardAiEmployeesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiEmployeesRoute: AiEmployeesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  WorkspaceSetupRoute: WorkspaceSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
